-- CREATE IF NOT EXISTS DATABASE TEST;
DROP TABLE IF EXISTS GoogleCrawler;

CREATE TABLE IF NOT EXISTS GoogleCrawler (
	Id INT PRIMARY KEY,
	Title VARCHAR(80) NOT NULL,
	Url VARCHAR(256) NOT NULL,
	Description VARCHAR(4000)
);

LOAD DATA LOCAL INFILE 'result.dat' INTO TABLE GoogleCrawler
	FIELDS TERMINATED BY '|*|'
	LINES TERMINATED BY '|**|';